---
- name: Configuration commune de tous les serveurs
  hosts: all
  become: true
  vars_files:
    - Inventories/group_vars/all.yml
    - Inventories/group_vars/vault.yml
  roles:
    - common
    - firewall

- name: Déploiement des serveurs web
  hosts: webservers
  become: true
  vars_files:
    - Inventories/group_vars/all.yml
    - Inventories/group_vars/vault.yml
  roles:
    - nginx
    - php

- name: Déploiement de la base de données
  hosts: dbservers
  become: true
  vars_files:
    - Inventories/group_vars/all.yml
    - Inventories/group_vars/vault.yml
  roles:
    - mysql
